In [1]:
import torch

In [18]:
a = torch.FloatTensor([[[0,1,0.5],[0.2,0.54,0.01],[0.4,0.2,0.9],[0.8,0.6,0.12]],[[0,1,0.5],[0.2,0.54,0.01],[0.4,0.2,0.9],[0.8,0.6,0.12]]])

In [21]:
a = torch.rand((32,256))

In [23]:
a

tensor([[0.1628, 0.5333, 0.7341,  ..., 0.5069, 0.3249, 0.8201],
        [0.8974, 0.7779, 0.1607,  ..., 0.9504, 0.0432, 0.9209],
        [0.7158, 0.4914, 0.8173,  ..., 0.3818, 0.1674, 0.8043],
        ...,
        [0.2153, 0.0496, 0.4359,  ..., 0.7258, 0.8718, 0.1148],
        [0.4283, 0.1132, 0.8964,  ..., 0.0051, 0.0622, 0.6229],
        [0.2421, 0.4626, 0.8242,  ..., 0.2408, 0.6740, 0.8112]])

In [24]:
dist = torch.pow(a, 2).sum(dim=1,keepdim=True)

In [27]:
dist = dist.expand(32,32)

In [28]:
dist = dist+dist.t()

In [29]:
dist

tensor([[183.7688, 173.5114, 176.9542,  ..., 182.4208, 165.7201, 177.9842],
        [173.5114, 163.2539, 166.6968,  ..., 172.1634, 155.4627, 167.7267],
        [176.9542, 166.6968, 170.1397,  ..., 175.6063, 158.9055, 171.1696],
        ...,
        [182.4208, 172.1634, 175.6063,  ..., 181.0729, 164.3722, 176.6362],
        [165.7201, 155.4627, 158.9055,  ..., 164.3722, 147.6714, 159.9355],
        [177.9842, 167.7267, 171.1696,  ..., 176.6362, 159.9355, 172.1995]])

In [30]:
dist.addmm_(1,-2,a,a.t())

tensor([[ 1.5259e-05,  4.6526e+01,  4.2201e+01,  ...,  4.4582e+01,
          4.5078e+01,  4.2092e+01],
        [ 4.6526e+01, -4.5776e-05,  4.4681e+01,  ...,  4.5669e+01,
          4.5534e+01,  4.2422e+01],
        [ 4.2201e+01,  4.4681e+01, -6.1035e-05,  ...,  3.8621e+01,
          4.3788e+01,  4.2694e+01],
        ...,
        [ 4.4582e+01,  4.5669e+01,  3.8621e+01,  ..., -1.5259e-05,
          4.5959e+01,  4.3680e+01],
        [ 4.5079e+01,  4.5534e+01,  4.3788e+01,  ...,  4.5959e+01,
         -1.5259e-05,  4.6189e+01],
        [ 4.2092e+01,  4.2422e+01,  4.2694e+01,  ...,  4.3680e+01,
          4.6189e+01,  1.5259e-05]])

In [31]:
dist = dist.clamp(min=1e-12).sqrt()

In [32]:
dist

tensor([[3.9062e-03, 6.8210e+00, 6.4962e+00,  ..., 6.6770e+00, 6.7140e+00,
         6.4879e+00],
        [6.8210e+00, 1.0000e-06, 6.6844e+00,  ..., 6.7579e+00, 6.7479e+00,
         6.5132e+00],
        [6.4962e+00, 6.6844e+00, 1.0000e-06,  ..., 6.2146e+00, 6.6172e+00,
         6.5341e+00],
        ...,
        [6.6770e+00, 6.7579e+00, 6.2146e+00,  ..., 1.0000e-06, 6.7793e+00,
         6.6091e+00],
        [6.7141e+00, 6.7479e+00, 6.6172e+00,  ..., 6.7793e+00, 1.0000e-06,
         6.7962e+00],
        [6.4879e+00, 6.5132e+00, 6.5341e+00,  ..., 6.6091e+00, 6.7962e+00,
         3.9062e-03]])

In [36]:
mask = torch.FloatTensor(13*[1]+2*[2] + 15*[3]+2*[4])

In [37]:
ma = mask.expand(32,32).eq(mask.expand(32,32).t())

In [38]:
ma

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 0, 1, 1],
        [0, 0, 0,  ..., 0, 1, 1]], dtype=torch.uint8)

In [48]:
x = torch.where(ma==1,torch.ByteTensor([0]),torch.ByteTensor([1]))

In [53]:
x

tensor([[1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        ...,
        [2, 2, 2,  ..., 1, 2, 2],
        [2, 2, 2,  ..., 2, 1, 1],
        [2, 2, 2,  ..., 2, 1, 1]], dtype=torch.uint8)

In [50]:
(x==0)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.uint8)

In [51]:
for i in x:
    i += 1

In [52]:
x

tensor([[1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        ...,
        [2, 2, 2,  ..., 1, 2, 2],
        [2, 2, 2,  ..., 2, 1, 1],
        [2, 2, 2,  ..., 2, 1, 1]], dtype=torch.uint8)

In [56]:
len(x)

32

In [57]:
x

tensor([[1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        ...,
        [2, 2, 2,  ..., 1, 2, 2],
        [2, 2, 2,  ..., 2, 1, 1],
        [2, 2, 2,  ..., 2, 1, 1]], dtype=torch.uint8)

In [58]:
y = []
y.append(x[0])

In [67]:
y = torch.ByteTensor([1]*32)

In [70]:
y = y.add(x[0])

In [71]:
y.add(x[2])

tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5], dtype=torch.uint8)

In [81]:
torch.cat((y,(x[3])),expand = True)

TypeError: cat() got an unexpected keyword argument 'expand'

In [77]:
a = torch.ByteTensor()

In [78]:
torch.cat((a, x[1]))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2], dtype=torch.uint8)

In [83]:
x.expand_as((1,x.size(0),x.size(1)))

TypeError: expand_as(): argument 'other' (position 1) must be Tensor, not tuple

In [88]:
a = torch.cat((a,x[1].view(1,32)))

In [89]:
b = torch.cat((a,x[2].view(1,32)))

In [90]:
b

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2]], dtype=torch.uint8)

In [91]:
b[0,1] = 100

In [92]:
b

tensor([[  1, 100,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2],
        [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   2,
           2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
           2,   2,   2,   2]], dtype=torch.uint8)

In [93]:
a

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2]], dtype=torch.uint8)

In [94]:
x

tensor([[1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        [1, 1, 1,  ..., 2, 2, 2],
        ...,
        [2, 2, 2,  ..., 1, 2, 2],
        [2, 2, 2,  ..., 2, 1, 1],
        [2, 2, 2,  ..., 2, 1, 1]], dtype=torch.uint8)

In [95]:
x==100

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], dtype=torch.uint8)

In [100]:
torch.any(x==3)

tensor(0, dtype=torch.uint8)

In [103]:
if(torch.any(x==2)):
    print('d')

d


In [104]:
a = []
for i in range(64):
    a.append(torch.rand((3,11,11)))

In [109]:
b = torch.Tensor(a)

ValueError: only one element tensors can be converted to Python scalars

In [114]:
torch.stack(a).size()

torch.Size([64, 3, 11, 11])

In [125]:
a = torch.zeros((1,2,3,20))

In [126]:
a[:,1,:,3:] = 1

In [127]:
a[:,0,1:3,:] = 2

In [128]:
a

tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0.],
          [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
           2., 2., 2.],
          [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
           2., 2., 2.]],

         [[0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1.],
          [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1.],
          [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1.]]]])

In [129]:
inv_idx = torch.arange(a.size(3)-1, -1,-1).long()

In [130]:
inv_idx

tensor([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,
         1,  0])

In [131]:
a.index_select(3, inv_idx)

tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0.],
          [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
           2., 2., 2.],
          [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
           2., 2., 2.]],

         [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           0., 0., 0.]]]])

In [124]:
a.size(3)

4